# Generated by Django 5.0.7 on 2024-07-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=100)),
                ("outline", models.TextField()),
                ("movie_url", models.URLField()),
            ],
        ),
    ]
