# Generated by Django 5.0.7 on 2024-07-30 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scraper",
            "0002_genre_movie_language_movie_released_on_movie_runtime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="runtime",
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name="movie",
            name="released_on",
            field=models.CharField(max_length=100),
        ),
    ]
