# Generated by Django 5.0.7 on 2024-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0003_remove_movie_runtime_movie_poster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.URLField(),
        ),
    ]
