# Generated by Django 5.0.7 on 2024-07-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_alter_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="audiencereviews",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="audiencescore",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="criticsreviews",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="criticsscore",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
